/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.GCobro;

import Controlador.ControladorGCobro;


/**
 *
 * @author Alex Altuve
 */
public class GestiondeCobros1 extends javax.swing.JPanel {
    ControladorGCobro control;
    /**
     * Creates new form GestiondeCobros1
     */
    public GestiondeCobros1(String ci) {
        initComponents();        
        control= new ControladorGCobro(Nombre,Cedula,Direccion, NumTar, NumTrans, Nota, Telefono, ListTel, Tarjeta, transferencia, efectivo, Valida,MontoCobrado,Servicios);
        control.ConsultarCobro(ci);
        ListTel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Valida = new javax.swing.ButtonGroup();
        Nombre = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NumTar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CerrarSesion = new rsbuttom.RSButtonMetro();
        jLabel17 = new javax.swing.JLabel();
        MontoCobrado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        NumTrans = new javax.swing.JTextField();
        Nota = new javax.swing.JTextField();
        Tarjeta = new javax.swing.JRadioButton();
        transferencia = new javax.swing.JRadioButton();
        efectivo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ListTel = new javax.swing.JComboBox<>();
        Telefono = new javax.swing.JTextField();
        Servicios = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JTextField();
        Direccion1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NumTar1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Cedula1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CerrarSesion1 = new rsbuttom.RSButtonMetro();
        jLabel20 = new javax.swing.JLabel();
        MontoCobrado1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        NumTrans1 = new javax.swing.JTextField();
        Nota1 = new javax.swing.JTextField();
        Tarjeta1 = new javax.swing.JRadioButton();
        transferencia1 = new javax.swing.JRadioButton();
        efectivo1 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ListTel1 = new javax.swing.JComboBox<>();
        Telefono1 = new javax.swing.JTextField();
        Servicios1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        Nombre.setEditable(false);
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });

        Direccion.setEditable(false);
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 64, 64));
        jLabel1.setText("Nombre Completo");

        NumTar.setEditable(false);
        NumTar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTarActionPerformed(evt);
            }
        });
        NumTar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumTarKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(64, 64, 64));
        jLabel10.setText("Dirección corta");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(64, 64, 64));
        jLabel11.setText("Num de trajeta");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(64, 64, 64));
        jLabel16.setText("Formas de Pago");

        Cedula.setEditable(false);
        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 64, 64));
        jLabel3.setText("Cédula");

        CerrarSesion.setBackground(new java.awt.Color(153, 204, 255));
        CerrarSesion.setText("Regresar");
        CerrarSesion.setColorHover(new java.awt.Color(204, 255, 255));
        CerrarSesion.setColorNormal(new java.awt.Color(153, 204, 255));
        CerrarSesion.setColorTextNormal(new java.awt.Color(0, 0, 0));
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(64, 64, 64));
        jLabel17.setText("Telefono");

        MontoCobrado.setEditable(false);
        MontoCobrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoCobradoActionPerformed(evt);
            }
        });
        MontoCobrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MontoCobradoKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(64, 64, 64));
        jLabel18.setText("Monto Cobrado");

        NumTrans.setEditable(false);
        NumTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTransActionPerformed(evt);
            }
        });
        NumTrans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumTransKeyTyped(evt);
            }
        });

        Nota.setEditable(false);
        Nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaActionPerformed(evt);
            }
        });
        Nota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NotaKeyTyped(evt);
            }
        });

        Tarjeta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tarjeta.setText("Tarjeta");
        Tarjeta.setContentAreaFilled(false);
        Tarjeta.setEnabled(false);
        Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaActionPerformed(evt);
            }
        });

        transferencia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        transferencia.setText("Transferencia");
        transferencia.setContentAreaFilled(false);
        transferencia.setEnabled(false);

        efectivo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        efectivo.setText("Efectivo");
        efectivo.setContentAreaFilled(false);
        efectivo.setEnabled(false);
        efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectivoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(64, 64, 64));
        jLabel13.setText("Num de Transferencia");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(64, 64, 64));
        jLabel14.setText("Observaciones");

        ListTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        ListTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTelActionPerformed(evt);
            }
        });

        Telefono.setEditable(false);
        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        Servicios.setEditable(false);
        Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosActionPerformed(evt);
            }
        });
        Servicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ServiciosKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(64, 64, 64));
        jLabel23.setText("Servicios");

        setBackground(new java.awt.Color(162, 215, 239));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/divsub_2.png"))); // NOI18N

        Nombre1.setEditable(false);
        Nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre1ActionPerformed(evt);
            }
        });
        Nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nombre1KeyTyped(evt);
            }
        });

        Direccion1.setEditable(false);
        Direccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Direccion1ActionPerformed(evt);
            }
        });
        Direccion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Direccion1KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 64, 64));
        jLabel2.setText("Nombre Completo");

        NumTar1.setEditable(false);
        NumTar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTar1ActionPerformed(evt);
            }
        });
        NumTar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumTar1KeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(64, 64, 64));
        jLabel12.setText("Dirección corta");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(64, 64, 64));
        jLabel15.setText("Num de trajeta");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(64, 64, 64));
        jLabel19.setText("Formas de Pago");

        Cedula1.setEditable(false);
        Cedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cedula1ActionPerformed(evt);
            }
        });
        Cedula1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cedula1KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 64, 64));
        jLabel5.setText("Cédula");

        CerrarSesion1.setBackground(new java.awt.Color(153, 204, 255));
        CerrarSesion1.setText("Regresar");
        CerrarSesion1.setColorHover(new java.awt.Color(204, 255, 255));
        CerrarSesion1.setColorNormal(new java.awt.Color(153, 204, 255));
        CerrarSesion1.setColorTextNormal(new java.awt.Color(0, 0, 0));
        CerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesion1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(64, 64, 64));
        jLabel20.setText("Telefono");

        MontoCobrado1.setEditable(false);
        MontoCobrado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoCobrado1ActionPerformed(evt);
            }
        });
        MontoCobrado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MontoCobrado1KeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(64, 64, 64));
        jLabel21.setText("Monto Cobrado");

        NumTrans1.setEditable(false);
        NumTrans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTrans1ActionPerformed(evt);
            }
        });
        NumTrans1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumTrans1KeyTyped(evt);
            }
        });

        Nota1.setEditable(false);
        Nota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nota1ActionPerformed(evt);
            }
        });
        Nota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nota1KeyTyped(evt);
            }
        });

        Tarjeta1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tarjeta1.setText("Tarjeta");
        Tarjeta1.setContentAreaFilled(false);
        Tarjeta1.setEnabled(false);
        Tarjeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tarjeta1ActionPerformed(evt);
            }
        });

        transferencia1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        transferencia1.setText("Transferencia");
        transferencia1.setContentAreaFilled(false);
        transferencia1.setEnabled(false);

        efectivo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        efectivo1.setText("Efectivo");
        efectivo1.setContentAreaFilled(false);
        efectivo1.setEnabled(false);
        efectivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectivo1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(64, 64, 64));
        jLabel22.setText("Num de Transferencia");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(64, 64, 64));
        jLabel24.setText("Observaciones");

        ListTel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        ListTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTel1ActionPerformed(evt);
            }
        });

        Telefono1.setEditable(false);
        Telefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Telefono1ActionPerformed(evt);
            }
        });
        Telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Telefono1KeyTyped(evt);
            }
        });

        Servicios1.setEditable(false);
        Servicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Servicios1ActionPerformed(evt);
            }
        });
        Servicios1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Servicios1KeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(64, 64, 64));
        jLabel25.setText("Servicios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ListTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Tarjeta1)
                                                    .addGap(74, 74, 74)
                                                    .addComponent(efectivo1)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(NumTar1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Cedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Servicios1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(MontoCobrado1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Nota1)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(transferencia1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NumTrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(CerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(jLabel20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Servicios1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ListTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tarjeta1)
                            .addComponent(efectivo1)
                            .addComponent(transferencia1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MontoCobrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NumTrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NumTar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(CerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped

    }//GEN-LAST:event_NombreKeyTyped

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped

    }//GEN-LAST:event_DireccionKeyTyped

    private void NumTarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTarActionPerformed

    private void NumTarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumTarKeyTyped

    }//GEN-LAST:event_NumTarKeyTyped

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped

    }//GEN-LAST:event_CedulaKeyTyped

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        GestiondeCobros destino = new GestiondeCobros();
        control.ConectarPanel(this, destino,  960, 639, 0, 0);
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void MontoCobradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoCobradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoCobradoActionPerformed

    private void MontoCobradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontoCobradoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoCobradoKeyTyped

    private void NumTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTransActionPerformed

    private void NumTransKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumTransKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTransKeyTyped

    private void NotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaActionPerformed

    private void NotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NotaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaKeyTyped

    private void TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TarjetaActionPerformed

    private void efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efectivoActionPerformed

    private void ListTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTelActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped

    }//GEN-LAST:event_TelefonoKeyTyped

    private void ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosActionPerformed

    private void ServiciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ServiciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosKeyTyped

    private void Nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre1ActionPerformed

    private void Nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nombre1KeyTyped

    }//GEN-LAST:event_Nombre1KeyTyped

    private void Direccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Direccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Direccion1ActionPerformed

    private void Direccion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Direccion1KeyTyped

    }//GEN-LAST:event_Direccion1KeyTyped

    private void NumTar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTar1ActionPerformed

    private void NumTar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumTar1KeyTyped

    }//GEN-LAST:event_NumTar1KeyTyped

    private void Cedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cedula1ActionPerformed

    private void Cedula1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cedula1KeyTyped

    }//GEN-LAST:event_Cedula1KeyTyped

    private void CerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesion1ActionPerformed
        GestiondeCobros destino = new GestiondeCobros();
        control.ConectarPanel(this, destino,  960, 639, 0, 0);
    }//GEN-LAST:event_CerrarSesion1ActionPerformed

    private void MontoCobrado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoCobrado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoCobrado1ActionPerformed

    private void MontoCobrado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontoCobrado1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoCobrado1KeyTyped

    private void NumTrans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTrans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTrans1ActionPerformed

    private void NumTrans1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumTrans1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTrans1KeyTyped

    private void Nota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nota1ActionPerformed

    private void Nota1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nota1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Nota1KeyTyped

    private void Tarjeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tarjeta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tarjeta1ActionPerformed

    private void efectivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectivo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efectivo1ActionPerformed

    private void ListTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTel1ActionPerformed

    private void Telefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Telefono1ActionPerformed

    private void Telefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Telefono1KeyTyped

    }//GEN-LAST:event_Telefono1KeyTyped

    private void Servicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Servicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Servicios1ActionPerformed

    private void Servicios1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Servicios1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Servicios1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Cedula1;
    private rsbuttom.RSButtonMetro CerrarSesion;
    private rsbuttom.RSButtonMetro CerrarSesion1;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Direccion1;
    private javax.swing.JComboBox<String> ListTel;
    private javax.swing.JComboBox<String> ListTel1;
    private javax.swing.JTextField MontoCobrado;
    private javax.swing.JTextField MontoCobrado1;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField Nota;
    private javax.swing.JTextField Nota1;
    private javax.swing.JTextField NumTar;
    private javax.swing.JTextField NumTar1;
    private javax.swing.JTextField NumTrans;
    private javax.swing.JTextField NumTrans1;
    private javax.swing.JTextField Servicios;
    private javax.swing.JTextField Servicios1;
    private javax.swing.JRadioButton Tarjeta;
    private javax.swing.JRadioButton Tarjeta1;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField Telefono1;
    private javax.swing.ButtonGroup Valida;
    private javax.swing.JRadioButton efectivo;
    private javax.swing.JRadioButton efectivo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton transferencia;
    private javax.swing.JRadioButton transferencia1;
    // End of variables declaration//GEN-END:variables
}
