/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.GCobro;

import Controlador.ControladorGCobro;

/**
 *
 * @author Alex Altuve
 */
public class RegistrarCobro extends javax.swing.JPanel {
    ControladorGCobro control;
    /**
     * Creates new form RegistrarCobro
     */
    public RegistrarCobro() {
        initComponents();
        control= new ControladorGCobro(Nombre,Cedula,Direccion, NumTar, NumTrans, Nota, Telefono, Error_Nombre, Error_Cedula, Error_NumTar, Error_NumTrans, Error_Telefono,ListTel, Tarjeta, transferencia, efectivo, Valida, MontoCobrado,Servicios);
        if(Tarjeta.isSelected()==false){
            NumTar.setEnabled(false);
        }
        if(transferencia.isSelected()==false){
            NumTrans.setEnabled(false);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Valida = new javax.swing.ButtonGroup();
        Nombre = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NumTar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelRound4 = new Modelo.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        Cedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        Error_Direccion = new javax.swing.JTextField();
        Error_Nombre = new javax.swing.JTextField();
        Error_Cedula = new javax.swing.JTextField();
        CerrarSesion = new rsbuttom.RSButtonMetro();
        jLabel17 = new javax.swing.JLabel();
        MontoCobrado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        NumTrans = new javax.swing.JTextField();
        Nota = new javax.swing.JTextField();
        Tarjeta = new javax.swing.JRadioButton();
        transferencia = new javax.swing.JRadioButton();
        efectivo = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ListTel = new javax.swing.JComboBox<>();
        Telefono = new javax.swing.JTextField();
        Servicios = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Error_Telefono = new javax.swing.JTextField();
        Error_Servicio = new javax.swing.JTextField();
        Error_Monto = new javax.swing.JTextField();
        Error_NumTar = new javax.swing.JTextField();
        Error_NumTrans = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JTextField();
        Direccion1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NumTar1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Cedula1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rSButtonMetro3 = new rsbuttom.RSButtonMetro();
        Error_Direccion1 = new javax.swing.JTextField();
        Error_Nombre1 = new javax.swing.JTextField();
        Error_Cedula1 = new javax.swing.JTextField();
        CerrarSesion1 = new rsbuttom.RSButtonMetro();
        jLabel21 = new javax.swing.JLabel();
        MontoCobrado1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        NumTrans1 = new javax.swing.JTextField();
        Nota1 = new javax.swing.JTextField();
        Tarjeta1 = new javax.swing.JRadioButton();
        transferencia1 = new javax.swing.JRadioButton();
        efectivo1 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ListTel1 = new javax.swing.JComboBox<>();
        Telefono1 = new javax.swing.JTextField();
        Servicios1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Error_Telefono1 = new javax.swing.JTextField();
        Error_Servicio1 = new javax.swing.JTextField();
        Error_Monto1 = new javax.swing.JTextField();
        Error_NumTar1 = new javax.swing.JTextField();
        Error_NumTrans1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });

        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 64, 64));
        jLabel1.setText("Nombre Completo");

        NumTar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTarActionPerformed(evt);
            }
        });
        NumTar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumTarKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(64, 64, 64));
        jLabel10.setText("Dirección corta");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(64, 64, 64));
        jLabel11.setText("Num de trajeta");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(64, 64, 64));
        jLabel16.setText("Formas de Pago");

        panelRound4.setBackground(new java.awt.Color(102, 102, 255));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos del paciente");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });
        Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 64, 64));
        jLabel3.setText("Cédula");

        rSButtonMetro2.setText("Registrar");
        rSButtonMetro2.setColorHover(new java.awt.Color(104, 255, 104));
        rSButtonMetro2.setColorNormal(new java.awt.Color(113, 226, 113));
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });

        Error_Direccion.setEditable(false);
        Error_Direccion.setBackground(new java.awt.Color(0,0,0,1));
        Error_Direccion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Direccion.setForeground(new java.awt.Color(255, 0, 0));
        Error_Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Direccion.setBorder(null);

        Error_Nombre.setEditable(false);
        Error_Nombre.setBackground(new java.awt.Color(0,0,0,1));
        Error_Nombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Nombre.setForeground(new java.awt.Color(255, 0, 0));
        Error_Nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Nombre.setBorder(null);

        Error_Cedula.setEditable(false);
        Error_Cedula.setBackground(new java.awt.Color(0,0,0,1));
        Error_Cedula.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Cedula.setForeground(new java.awt.Color(255, 0, 0));
        Error_Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Cedula.setBorder(null);

        CerrarSesion.setBackground(new java.awt.Color(153, 204, 255));
        CerrarSesion.setText("Regresar");
        CerrarSesion.setColorHover(new java.awt.Color(204, 255, 255));
        CerrarSesion.setColorNormal(new java.awt.Color(153, 204, 255));
        CerrarSesion.setColorTextNormal(new java.awt.Color(0, 0, 0));
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(64, 64, 64));
        jLabel17.setText("Telefono");

        MontoCobrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoCobradoActionPerformed(evt);
            }
        });
        MontoCobrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MontoCobradoKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(64, 64, 64));
        jLabel18.setText("Monto Cobrado");

        NumTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTransActionPerformed(evt);
            }
        });
        NumTrans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumTransKeyTyped(evt);
            }
        });

        Nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaActionPerformed(evt);
            }
        });
        Nota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NotaKeyTyped(evt);
            }
        });

        Tarjeta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tarjeta.setText("Tarjeta");
        Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaActionPerformed(evt);
            }
        });

        transferencia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        transferencia.setText("Transferencia");
        transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaActionPerformed(evt);
            }
        });

        efectivo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        efectivo.setText("Efectivo");
        efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectivoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(64, 64, 64));
        jLabel13.setText("Num de Transferencia");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(64, 64, 64));
        jLabel14.setText("Observaciones");

        ListTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        ListTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTelActionPerformed(evt);
            }
        });

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });

        Servicios.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosActionPerformed(evt);
            }
        });
        Servicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ServiciosKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(64, 64, 64));
        jLabel20.setText("Servicios");

        Error_Telefono.setEditable(false);
        Error_Telefono.setBackground(new java.awt.Color(0,0,0,1));
        Error_Telefono.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Telefono.setForeground(new java.awt.Color(255, 0, 0));
        Error_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Telefono.setBorder(null);

        Error_Servicio.setEditable(false);
        Error_Servicio.setBackground(new java.awt.Color(0,0,0,1));
        Error_Servicio.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Servicio.setForeground(new java.awt.Color(255, 0, 0));
        Error_Servicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Servicio.setBorder(null);

        Error_Monto.setEditable(false);
        Error_Monto.setBackground(new java.awt.Color(0,0,0,1));
        Error_Monto.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Monto.setForeground(new java.awt.Color(255, 0, 0));
        Error_Monto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Monto.setBorder(null);
        Error_Monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_MontoActionPerformed(evt);
            }
        });

        Error_NumTar.setEditable(false);
        Error_NumTar.setBackground(new java.awt.Color(0,0,0,1));
        Error_NumTar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_NumTar.setForeground(new java.awt.Color(255, 0, 0));
        Error_NumTar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_NumTar.setBorder(null);
        Error_NumTar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_NumTarActionPerformed(evt);
            }
        });

        Error_NumTrans.setEditable(false);
        Error_NumTrans.setBackground(new java.awt.Color(0,0,0,1));
        Error_NumTrans.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_NumTrans.setForeground(new java.awt.Color(255, 0, 0));
        Error_NumTrans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_NumTrans.setBorder(null);

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/divsup.png"))); // NOI18N

        Nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre1ActionPerformed(evt);
            }
        });
        Nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nombre1KeyTyped(evt);
            }
        });

        Direccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Direccion1ActionPerformed(evt);
            }
        });
        Direccion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Direccion1KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 64, 64));
        jLabel5.setText("Nombre Completo");

        NumTar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTar1ActionPerformed(evt);
            }
        });
        NumTar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumTar1KeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(64, 64, 64));
        jLabel12.setText("Dirección corta");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(64, 64, 64));
        jLabel15.setText("Num de trajeta");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(64, 64, 64));
        jLabel19.setText("Formas de Pago");

        Cedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cedula1ActionPerformed(evt);
            }
        });
        Cedula1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cedula1KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 64, 64));
        jLabel7.setText("Cédula");

        rSButtonMetro3.setText("Registrar");
        rSButtonMetro3.setColorHover(new java.awt.Color(104, 255, 104));
        rSButtonMetro3.setColorNormal(new java.awt.Color(113, 226, 113));
        rSButtonMetro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro3ActionPerformed(evt);
            }
        });

        Error_Direccion1.setEditable(false);
        Error_Direccion1.setBackground(new java.awt.Color(0,0,0,1));
        Error_Direccion1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Direccion1.setForeground(new java.awt.Color(255, 0, 0));
        Error_Direccion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Direccion1.setBorder(null);

        Error_Nombre1.setEditable(false);
        Error_Nombre1.setBackground(new java.awt.Color(0,0,0,1));
        Error_Nombre1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Nombre1.setForeground(new java.awt.Color(255, 0, 0));
        Error_Nombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Nombre1.setBorder(null);

        Error_Cedula1.setEditable(false);
        Error_Cedula1.setBackground(new java.awt.Color(0,0,0,1));
        Error_Cedula1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Cedula1.setForeground(new java.awt.Color(255, 0, 0));
        Error_Cedula1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Cedula1.setBorder(null);

        CerrarSesion1.setBackground(new java.awt.Color(153, 204, 255));
        CerrarSesion1.setText("Regresar");
        CerrarSesion1.setColorHover(new java.awt.Color(204, 255, 255));
        CerrarSesion1.setColorNormal(new java.awt.Color(153, 204, 255));
        CerrarSesion1.setColorTextNormal(new java.awt.Color(0, 0, 0));
        CerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesion1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(64, 64, 64));
        jLabel21.setText("Telefono");

        MontoCobrado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoCobrado1ActionPerformed(evt);
            }
        });
        MontoCobrado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MontoCobrado1KeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(64, 64, 64));
        jLabel22.setText("Monto Cobrado");

        NumTrans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumTrans1ActionPerformed(evt);
            }
        });
        NumTrans1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumTrans1KeyTyped(evt);
            }
        });

        Nota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nota1ActionPerformed(evt);
            }
        });
        Nota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nota1KeyTyped(evt);
            }
        });

        Tarjeta1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Tarjeta1.setText("Tarjeta");
        Tarjeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tarjeta1ActionPerformed(evt);
            }
        });

        transferencia1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        transferencia1.setText("Transferencia");
        transferencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferencia1ActionPerformed(evt);
            }
        });

        efectivo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        efectivo1.setText("Efectivo");
        efectivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efectivo1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(64, 64, 64));
        jLabel23.setText("Num de Transferencia");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(64, 64, 64));
        jLabel24.setText("Observaciones");

        ListTel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        ListTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTel1ActionPerformed(evt);
            }
        });

        Telefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Telefono1ActionPerformed(evt);
            }
        });
        Telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Telefono1KeyTyped(evt);
            }
        });

        Servicios1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Servicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Servicios1ActionPerformed(evt);
            }
        });
        Servicios1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Servicios1KeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(64, 64, 64));
        jLabel25.setText("Servicios");

        Error_Telefono1.setEditable(false);
        Error_Telefono1.setBackground(new java.awt.Color(0,0,0,1));
        Error_Telefono1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Telefono1.setForeground(new java.awt.Color(255, 0, 0));
        Error_Telefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Telefono1.setBorder(null);

        Error_Servicio1.setEditable(false);
        Error_Servicio1.setBackground(new java.awt.Color(0,0,0,1));
        Error_Servicio1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Servicio1.setForeground(new java.awt.Color(255, 0, 0));
        Error_Servicio1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Servicio1.setBorder(null);

        Error_Monto1.setEditable(false);
        Error_Monto1.setBackground(new java.awt.Color(0,0,0,1));
        Error_Monto1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Monto1.setForeground(new java.awt.Color(255, 0, 0));
        Error_Monto1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Monto1.setBorder(null);
        Error_Monto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_Monto1ActionPerformed(evt);
            }
        });

        Error_NumTar1.setEditable(false);
        Error_NumTar1.setBackground(new java.awt.Color(0,0,0,1));
        Error_NumTar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_NumTar1.setForeground(new java.awt.Color(255, 0, 0));
        Error_NumTar1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_NumTar1.setBorder(null);
        Error_NumTar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_NumTar1ActionPerformed(evt);
            }
        });

        Error_NumTrans1.setEditable(false);
        Error_NumTrans1.setBackground(new java.awt.Color(0,0,0,1));
        Error_NumTrans1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_NumTrans1.setForeground(new java.awt.Color(255, 0, 0));
        Error_NumTrans1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_NumTrans1.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Registro de cobro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(Error_Servicio1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Error_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Error_Cedula1)
                                    .addComponent(Cedula1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Tarjeta1)
                                        .addGap(85, 85, 85)
                                        .addComponent(efectivo1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ListTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Error_Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Servicios1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(transferencia1)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Direccion1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Error_Direccion1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(MontoCobrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Error_Monto1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Error_NumTrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButtonMetro3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NumTar1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(116, 116, 116)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NumTrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(Error_NumTar1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(CerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(393, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Error_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error_Cedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error_Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ListTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Error_Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(MontoCobrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Error_Monto1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Servicios1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Error_Servicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tarjeta1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(efectivo1)
                                .addComponent(transferencia1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Error_NumTrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButtonMetro3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(437, 437, 437)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(NumTar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(NumTrans1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Error_NumTar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(CerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){

            Error_Nombre.setText("No se aceptan caracteres especiales ni números");

            evt.consume();
        }
    }//GEN-LAST:event_NombreKeyTyped

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;
        boolean numeros= (key >= 48 && key <= 57);
        if (!(minusculas || mayusculas || espacio || numeros)){

            Error_Direccion.setText("No se aceptan caracteres especiales.");

            evt.consume();
        }
    }//GEN-LAST:event_DireccionKeyTyped

    private void NumTarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTarActionPerformed

    private void NumTarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumTarKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_NumTar.setText("No se aceptan caracteres especiales ni letras");
            evt.consume();
        }
        if (NumTar.getText().trim().length() >=18) {

            Error_NumTar.setText("La cédula debe tener 16-18 dígitos");
            evt.consume();
        }
    }//GEN-LAST:event_NumTarKeyTyped

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Cedula.setText("No se aceptan caracteres especiales ni letras");
            evt.consume();
        }
        if (Cedula.getText().trim().length() >=8) {

            Error_Cedula.setText("El N° de tarjeta debe tener 6-8 dígitos");
            evt.consume();
        }
    }//GEN-LAST:event_CedulaKeyTyped

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        if(control.RegistrarCobro()){
            GestiondeCobros destino = new GestiondeCobros();
            control.ConectarPanel(this, destino,  960, 639, 0, 0);
        }
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        GestiondeCobros destino = new GestiondeCobros();
        control.ConectarPanel(this, destino,  960, 639, 0, 0);
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void MontoCobradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoCobradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoCobradoActionPerformed

    private void MontoCobradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontoCobradoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Monto.setText("No se aceptan caracteres especiales ni letras");

            evt.consume();
        }
    }//GEN-LAST:event_MontoCobradoKeyTyped

    private void NumTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTransActionPerformed

    private void NumTransKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumTransKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_NumTrans.setText("No se aceptan caracteres especiales ni letras");
            evt.consume();
        }
        if (NumTrans.getText().trim().length() >=9) {

            Error_NumTrans.setText("El N° de transferencia debe tener 9 dígitos");
            evt.consume();
        }
    }//GEN-LAST:event_NumTransKeyTyped

    private void NotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaActionPerformed

    private void NotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NotaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaKeyTyped

    private void TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaActionPerformed
        if(Tarjeta.isSelected()==true){
            NumTar.setEnabled(true);
            NumTrans.setEnabled(false);
        }
    }//GEN-LAST:event_TarjetaActionPerformed

    private void transferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaActionPerformed
        if(transferencia.isSelected()==true){
            NumTar.setEnabled(false);
            NumTrans.setEnabled(true);

        }
    }//GEN-LAST:event_transferenciaActionPerformed

    private void efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectivoActionPerformed
        if(efectivo.isSelected()==true){
            NumTar.setEnabled(false);
            NumTrans.setEnabled(false);
        }
    }//GEN-LAST:event_efectivoActionPerformed

    private void ListTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTelActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Telefono.setText("No se aceptan caracteres especiales ni letras");

            evt.consume();
        }
        if (Telefono.getText().trim().length() >=7) {

            Error_Telefono.setText("No debe ingresar mas de 7 digitos");

            evt.consume();
        }
    }//GEN-LAST:event_TelefonoKeyTyped

    private void ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosActionPerformed

    private void ServiciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ServiciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiciosKeyTyped

    private void Error_MontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_MontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_MontoActionPerformed

    private void Error_NumTarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_NumTarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_NumTarActionPerformed

    private void Nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre1ActionPerformed

    private void Nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nombre1KeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){

            Error_Nombre.setText("No se aceptan caracteres especiales ni números");

            evt.consume();
        }
    }//GEN-LAST:event_Nombre1KeyTyped

    private void Direccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Direccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Direccion1ActionPerformed

    private void Direccion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Direccion1KeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;
        boolean numeros= (key >= 48 && key <= 57);
        if (!(minusculas || mayusculas || espacio || numeros)){

            Error_Direccion.setText("No se aceptan caracteres especiales.");

            evt.consume();
        }
    }//GEN-LAST:event_Direccion1KeyTyped

    private void NumTar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTar1ActionPerformed

    private void NumTar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumTar1KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_NumTar.setText("No se aceptan caracteres especiales ni letras");
            evt.consume();
        }
        if (NumTar.getText().trim().length() >=18) {

            Error_NumTar.setText("La cédula debe tener 16-18 dígitos");
            evt.consume();
        }
    }//GEN-LAST:event_NumTar1KeyTyped

    private void Cedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cedula1ActionPerformed

    private void Cedula1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cedula1KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Cedula.setText("No se aceptan caracteres especiales ni letras");
            evt.consume();
        }
        if (Cedula.getText().trim().length() >=8) {

            Error_Cedula.setText("El N° de tarjeta debe tener 6-8 dígitos");
            evt.consume();
        }
    }//GEN-LAST:event_Cedula1KeyTyped

    private void rSButtonMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro3ActionPerformed
        if(control.RegistrarCobro()){
            GestiondeCobros destino = new GestiondeCobros();
            control.ConectarPanel(this, destino,  960, 639, 0, 0);
        }
    }//GEN-LAST:event_rSButtonMetro3ActionPerformed

    private void CerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesion1ActionPerformed
        GestiondeCobros destino = new GestiondeCobros();
        control.ConectarPanel(this, destino,  960, 639, 0, 0);
    }//GEN-LAST:event_CerrarSesion1ActionPerformed

    private void MontoCobrado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoCobrado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoCobrado1ActionPerformed

    private void MontoCobrado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontoCobrado1KeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Monto.setText("No se aceptan caracteres especiales ni letras");

            evt.consume();
        }
    }//GEN-LAST:event_MontoCobrado1KeyTyped

    private void NumTrans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumTrans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumTrans1ActionPerformed

    private void NumTrans1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumTrans1KeyTyped
        int key = evt.getKeyChar();
        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_NumTrans.setText("No se aceptan caracteres especiales ni letras");
            evt.consume();
        }
        if (NumTrans.getText().trim().length() >=9) {

            Error_NumTrans.setText("El N° de transferencia debe tener 9 dígitos");
            evt.consume();
        }
    }//GEN-LAST:event_NumTrans1KeyTyped

    private void Nota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nota1ActionPerformed

    private void Nota1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nota1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Nota1KeyTyped

    private void Tarjeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tarjeta1ActionPerformed
        if(Tarjeta.isSelected()==true){
            NumTar.setEnabled(true);
            NumTrans.setEnabled(false);
        }
    }//GEN-LAST:event_Tarjeta1ActionPerformed

    private void transferencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferencia1ActionPerformed
        if(transferencia.isSelected()==true){
            NumTar.setEnabled(false);
            NumTrans.setEnabled(true);

        }
    }//GEN-LAST:event_transferencia1ActionPerformed

    private void efectivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efectivo1ActionPerformed
        if(efectivo.isSelected()==true){
            NumTar.setEnabled(false);
            NumTrans.setEnabled(false);
        }
    }//GEN-LAST:event_efectivo1ActionPerformed

    private void ListTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTel1ActionPerformed

    private void Telefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Telefono1ActionPerformed

    private void Telefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Telefono1KeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Telefono.setText("No se aceptan caracteres especiales ni letras");

            evt.consume();
        }
        if (Telefono.getText().trim().length() >=7) {

            Error_Telefono.setText("No debe ingresar mas de 7 digitos");

            evt.consume();
        }
    }//GEN-LAST:event_Telefono1KeyTyped

    private void Servicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Servicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Servicios1ActionPerformed

    private void Servicios1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Servicios1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Servicios1KeyTyped

    private void Error_Monto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_Monto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_Monto1ActionPerformed

    private void Error_NumTar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_NumTar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_NumTar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cedula;
    private javax.swing.JTextField Cedula1;
    private rsbuttom.RSButtonMetro CerrarSesion;
    private rsbuttom.RSButtonMetro CerrarSesion1;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Direccion1;
    private javax.swing.JTextField Error_Cedula;
    private javax.swing.JTextField Error_Cedula1;
    private javax.swing.JTextField Error_Direccion;
    private javax.swing.JTextField Error_Direccion1;
    private javax.swing.JTextField Error_Monto;
    private javax.swing.JTextField Error_Monto1;
    private javax.swing.JTextField Error_Nombre;
    private javax.swing.JTextField Error_Nombre1;
    private javax.swing.JTextField Error_NumTar;
    private javax.swing.JTextField Error_NumTar1;
    private javax.swing.JTextField Error_NumTrans;
    private javax.swing.JTextField Error_NumTrans1;
    private javax.swing.JTextField Error_Servicio;
    private javax.swing.JTextField Error_Servicio1;
    private javax.swing.JTextField Error_Telefono;
    private javax.swing.JTextField Error_Telefono1;
    private javax.swing.JComboBox<String> ListTel;
    private javax.swing.JComboBox<String> ListTel1;
    private javax.swing.JTextField MontoCobrado;
    private javax.swing.JTextField MontoCobrado1;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Nombre1;
    private javax.swing.JTextField Nota;
    private javax.swing.JTextField Nota1;
    private javax.swing.JTextField NumTar;
    private javax.swing.JTextField NumTar1;
    private javax.swing.JTextField NumTrans;
    private javax.swing.JTextField NumTrans1;
    private javax.swing.JTextField Servicios;
    private javax.swing.JTextField Servicios1;
    private javax.swing.JRadioButton Tarjeta;
    private javax.swing.JRadioButton Tarjeta1;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField Telefono1;
    private javax.swing.ButtonGroup Valida;
    private javax.swing.JRadioButton efectivo;
    private javax.swing.JRadioButton efectivo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private Modelo.PanelRound panelRound4;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private rsbuttom.RSButtonMetro rSButtonMetro3;
    private javax.swing.JRadioButton transferencia;
    private javax.swing.JRadioButton transferencia1;
    // End of variables declaration//GEN-END:variables
}
