/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.GOdontologo;

import Controlador.ControladorGOdontologo;

import Modelo.Conexion;


import java.awt.Color;

import java.sql.Connection;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class GestionOdontologos extends javax.swing.JPanel {

    ControladorGOdontologo control;
///////////////////////
    String CeduNom;
   
////////////////
   
    

    /**
     * Creates new form GestionOdontologos1
     */
    public GestionOdontologos() {
        initComponents();
        control = new ControladorGOdontologo(TablaOdontologos);
        control.LLenarTablaOdontologo();
    }

    public GestionOdontologos(String CeduNom) {
        this.CeduNom = CeduNom;
        initComponents();
        control = new ControladorGOdontologo(TablaOdontologos);
        control.LLenarTablaOdontologo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BModificarP = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneO = new javax.swing.JScrollPane();
        TablaOdontologos = new javax.swing.JTable();
        BuscarTodo = new javax.swing.JTextField();
        rSButtonMetro1 = new rsbuttom.RSButtonMetro();
        BModi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelRound1 = new Modelo.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        BModificarP.setBackground(new java.awt.Color(84, 84, 246));
        BModificarP.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BModificarP.setForeground(new java.awt.Color(255, 255, 255));
        BModificarP.setText("Modificar Perfil");
        BModificarP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BModificarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BModificarPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BModificarPMouseExited(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(254, 219, 254));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 6 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TablaOdontologos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneO.setViewportView(TablaOdontologos);

        BuscarTodo.setBackground(new java.awt.Color(204, 204, 204));
        BuscarTodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BuscarTodo.setForeground(new java.awt.Color(255, 255, 255));
        BuscarTodo.setText("Ingrese datos del odontólogo...");
        BuscarTodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BuscarTodoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BuscarTodoFocusLost(evt);
            }
        });
        BuscarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarTodoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarTodoMouseExited(evt);
            }
        });
        BuscarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTodoActionPerformed(evt);
            }
        });
        BuscarTodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarTodoKeyPressed(evt);
            }
        });

        rSButtonMetro1.setText("Agregar");
        rSButtonMetro1.setColorHover(new java.awt.Color(104, 255, 104));
        rSButtonMetro1.setColorNormal(new java.awt.Color(113, 226, 113));
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });

        BModi.setBackground(new java.awt.Color(0, 0, 102));
        BModi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BModi.setForeground(new java.awt.Color(255, 255, 255));
        BModi.setText("Consultar");
        BModi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BModi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BModiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BModiMouseExited(evt);
            }
        });
        BModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Listado de odontólogos");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contacto2.png"))); // NOI18N

        panelRound1.setBackground(new java.awt.Color(199, 236, 236));
        panelRound1.setRoundBottomLeft(200);

        jLabel4.setBackground(new java.awt.Color(0, 0, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestión");

        jLabel5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("odontólogos");

        jLabel6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("de");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(199, 236, 236));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 6 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(194, 194, 194)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BModi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BuscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPaneO, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneO, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BModi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BModificarPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BModificarPMouseEntered

    }//GEN-LAST:event_BModificarPMouseEntered

    private void BModificarPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BModificarPMouseExited

    }//GEN-LAST:event_BModificarPMouseExited

    private void BuscarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarTodoActionPerformed

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        RegistrarOdontologo destino = new RegistrarOdontologo();
        control.ConectarPanel(jPanel2, destino, 960, 639, 1, 0);
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void BuscarTodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarTodoKeyPressed

        String[] columna = {"Nombre", "Cedula", "Telefono", "Correo", "Usuario", "Clave", "F. Ingreso", "Especialidad"}; // se modifico
        String[] registros = new String[8];

        DefaultTableModel dtm = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String ssql = "SELECT *FROM odontologos WHERE Nombre LIKE '%" + BuscarTodo.getText() + "%' "
                + "OR Cedula LIKE '%" + BuscarTodo.getText() + "%'"
                + "OR Correo LIKE '%" + BuscarTodo.getText() + "%'"
                + "OR Telefono LIKE '%" + BuscarTodo.getText() + "%'"
                + "OR Especialidad LIKE '%" + BuscarTodo.getText() + "%'";
        try {
            Connection cn = Conexion.conectarBD();
            Statement stm = (Statement) cn.createStatement();
            ResultSet res = stm.executeQuery(ssql);

            while (res.next()) {

                registros[0] = res.getString(1); //nombre
                registros[1] = res.getString(2); //cedula
                registros[2] = res.getString(4); //telefono
                registros[3] = res.getString(5); //correo               
                registros[4] = res.getString(7); //user
                registros[5] = res.getString(8); // clave
                registros[6] = res.getString(9); // Fecha Ingreso
                registros[7] = res.getString(10); //especialidad

                dtm.addRow(registros);
            }
            TablaOdontologos.setModel(dtm);
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al ingresarlo en la BD " + e);
            JOptionPane.showMessageDialog(null, "¡Contacte al administrador!");
        }
    }//GEN-LAST:event_BuscarTodoKeyPressed

    
    
    
    private void BModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModiActionPerformed
         
        int fila=TablaOdontologos.getSelectedRow(); //llamar tabla odontologo
    if (fila>-1) {
        String Cedula_new= TablaOdontologos.getValueAt(fila, 1).toString().trim();
           
        GestionOdontologos1 destino = new GestionOdontologos1(Cedula_new);
        control.ConectarPanel(jPanel2, destino,  960, 639, 0, 0);  
       
    }else{
        JOptionPane.showMessageDialog(null, "Debe seleccionar un odontólogo antes de consultar");
    }
      
    }//GEN-LAST:event_BModiActionPerformed

    private void BModiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BModiMouseEntered
        BModi.setBackground(new Color(4,119,255));
    }//GEN-LAST:event_BModiMouseEntered

    private void BModiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BModiMouseExited
         BModi.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_BModiMouseExited

    private void BuscarTodoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarTodoFocusGained
        
        if(BuscarTodo.getText().equals("Ingrese datos del odontólogo...")){
            BuscarTodo.setText("");
            
        }
        
        BuscarTodo.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BuscarTodoFocusGained

    private void BuscarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarTodoMouseClicked
        BuscarTodo.setBackground(new Color(255,255,255));
        BuscarTodo.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_BuscarTodoMouseClicked

    private void BuscarTodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarTodoMouseExited
        
    }//GEN-LAST:event_BuscarTodoMouseExited

    private void BuscarTodoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarTodoFocusLost
        if(BuscarTodo.getText().trim().equals("") ){
            BuscarTodo.setText("Ingrese datos del odontólogo...");
            
        }
        
        BuscarTodo.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BuscarTodoFocusLost
 
    
    /*public void PlaceHolder(){
        JPlaceHolderTextField up = new JPlaceHolderTextField("Escriba",BuscarTodo);
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModi;
    private javax.swing.JButton BModificarP;
    private javax.swing.JTextField BuscarTodo;
    private javax.swing.JTable TablaOdontologos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPaneO;
    private Modelo.PanelRound panelRound1;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
    // End of variables declaration//GEN-END:variables
}
