

package Vista.GPaciente;

import java.awt.Color;
import Controlador.ControladorGHistoriaM;

/**
 *
 * @author sofiaarasme
 */
public class GestionHistoria extends javax.swing.JPanel {
    ControladorGHistoriaM control;
    public static String cedula_update = "";
    private static String MENSAJE = "Los datos básicos del paciente solo pueden modificarse en la pestaña anterior.";

    /**
     * Creates new form GestionHistoria
     */
    public GestionHistoria() {
        initComponents();
        
        cedula_update = GestionPacientes.Cedula_new;
        control= new ControladorGHistoriaM(Txt_Nombre, Txt_Cedula, Txt_Edad, Txt_Sexo, Txt_Telefono, Txt_Direccion, Txt_Observaciones, Txt_NomContacto,Txt_TelContacto, Txt_Parentesco, Txt_Especificacion1, Txt_Especificacion2, Txt_Especificacion3, Txt_Especificacion4, Txt_Especificacion5, Txt_Especificacion6,Txt_Habito, Txt_Motivo,RB1, RB11, RB2, RB22, RB3, RB33, RB4, RB44, RB5, RB55, RB6, RB66, RB7, RB77, RB8, RB88, RB9, RB99, RBA, RBAA, RBB, RBBB,buttonGroup1, buttonGroup10, buttonGroup11, buttonGroup2, buttonGroup3, buttonGroup4, buttonGroup5, buttonGroup6, buttonGroup7, buttonGroup8, buttonGroup9,Check_boca, Check_cara, Check_cuello, Check_Ortodoncia, Check_Cirugia, Check_Periodoncia, Check_Implantes, Check_Endodoncia, Check_Restauracion, Txt_Otras_Obs);
        control.CargarDatosPacienteHM(cedula_update);
        control.CargarDatosHistoria(cedula_update);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new Modelo.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        panelRound2 = new Modelo.PanelRound();
        CerrarSesion = new rsbuttom.RSButtonMetro();
        DescargarDiagramas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Sexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        Txt_Cedula = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        Txt_Edad = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Txt_Error = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_Telefono = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        Txt_Direccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        Txt_Observaciones = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Txt_NomContacto = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        Txt_Especificacion3 = new javax.swing.JTextField();
        Txt_Parentesco = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        RB3 = new javax.swing.JRadioButton();
        jSeparator19 = new javax.swing.JSeparator();
        RB33 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB1 = new javax.swing.JRadioButton();
        RB11 = new javax.swing.JRadioButton();
        RB22 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        Txt_TelContacto = new javax.swing.JTextField();
        Txt_Especificacion1 = new javax.swing.JTextField();
        Txt_Especificacion2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        RB4 = new javax.swing.JRadioButton();
        RB44 = new javax.swing.JRadioButton();
        Txt_Especificacion4 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        RB5 = new javax.swing.JRadioButton();
        RB55 = new javax.swing.JRadioButton();
        Txt_Especificacion5 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        RB6 = new javax.swing.JRadioButton();
        RB66 = new javax.swing.JRadioButton();
        Txt_Especificacion6 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Txt_Habito = new javax.swing.JTextField();
        RB7 = new javax.swing.JRadioButton();
        RB77 = new javax.swing.JRadioButton();
        RB8 = new javax.swing.JRadioButton();
        RB88 = new javax.swing.JRadioButton();
        RB9 = new javax.swing.JRadioButton();
        RB99 = new javax.swing.JRadioButton();
        RBA = new javax.swing.JRadioButton();
        RBAA = new javax.swing.JRadioButton();
        RBB = new javax.swing.JRadioButton();
        RBBB = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Check_Restauracion = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        Check_cuello = new javax.swing.JCheckBox();
        Check_cara = new javax.swing.JCheckBox();
        jLabel37 = new javax.swing.JLabel();
        Txt_Motivo = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Check_boca = new javax.swing.JCheckBox();
        Check_Ortodoncia = new javax.swing.JCheckBox();
        Check_Cirugia = new javax.swing.JCheckBox();
        Check_Periodoncia = new javax.swing.JCheckBox();
        Check_Implantes = new javax.swing.JCheckBox();
        Check_Endodoncia = new javax.swing.JCheckBox();
        jLabel44 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txt_Otras_Obs = new javax.swing.JTextPane();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        Txt_Error_Tel = new javax.swing.JLabel();
        Txt_Error_Nom = new javax.swing.JLabel();
        Txt_Error_Par = new javax.swing.JLabel();
        GuardarHistoria = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        panelRound1.setBackground(new java.awt.Color(174, 202, 229));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound1MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GESTIONAR HISTORIA");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelRound2.setBackground(new java.awt.Color(174, 202, 229));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound2MouseClicked(evt);
            }
        });
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CerrarSesion.setText("Regresar");
        CerrarSesion.setColorHover(new java.awt.Color(102, 204, 255));
        CerrarSesion.setColorNormal(new java.awt.Color(153, 255, 204));
        CerrarSesion.setColorTextNormal(new java.awt.Color(0, 0, 0));
        CerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        panelRound2.add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 90, 20));

        DescargarDiagramas.setBackground(new java.awt.Color(153, 51, 255));
        DescargarDiagramas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DescargarDiagramas.setForeground(new java.awt.Color(255, 255, 255));
        DescargarDiagramas.setText("Descargar Diagramas");
        DescargarDiagramas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DescargarDiagramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DescargarDiagramasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DescargarDiagramasMouseExited(evt);
            }
        });
        DescargarDiagramas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargarDiagramasActionPerformed(evt);
            }
        });
        panelRound2.add(DescargarDiagramas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 270, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 230, 10));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Especifique:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 70, -1));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 74, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("HISTORIA MÉDICA GENERAL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 280, -1));

        Txt_Sexo.setEditable(false);
        Txt_Sexo.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Sexo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Sexo.setText("jTextField1");
        Txt_Sexo.setBorder(null);
        Txt_Sexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_SexoMouseClicked(evt);
            }
        });
        jPanel2.add(Txt_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 104, 90, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Dirección:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 80, -1));

        Txt_Nombre.setEditable(false);
        Txt_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Nombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Nombre.setText("jTextField1");
        Txt_Nombre.setBorder(null);
        Txt_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_NombreMouseClicked(evt);
            }
        });
        Txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NombreActionPerformed(evt);
            }
        });
        jPanel2.add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 63, 200, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 150, 10));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Cédula:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 70, -1));

        Txt_Cedula.setEditable(false);
        Txt_Cedula.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Cedula.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Cedula.setText("jTextField1");
        Txt_Cedula.setBorder(null);
        Txt_Cedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_CedulaMouseClicked(evt);
            }
        });
        jPanel2.add(Txt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 63, 200, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 200, 10));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Nombre y Apellido:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, -1));

        Txt_Edad.setEditable(false);
        Txt_Edad.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Edad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Edad.setText("jTextField1");
        Txt_Edad.setBorder(null);
        Txt_Edad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_EdadMouseClicked(evt);
            }
        });
        jPanel2.add(Txt_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 63, 100, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 70, 10));

        Txt_Error.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Error.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(Txt_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 530, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Observaciones generales:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, -1));

        Txt_Telefono.setEditable(false);
        Txt_Telefono.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Telefono.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Telefono.setText("jTextField1");
        Txt_Telefono.setBorder(null);
        Txt_Telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_TelefonoMouseClicked(evt);
            }
        });
        jPanel2.add(Txt_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 104, 180, -1));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, 10));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Parentesco:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 90, -1));

        Txt_Direccion.setEditable(false);
        Txt_Direccion.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Direccion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Direccion.setText("jTextField1");
        Txt_Direccion.setBorder(null);
        Txt_Direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_DireccionMouseClicked(evt);
            }
        });
        jPanel2.add(Txt_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 104, 230, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Sexo:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, -1));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 110, 10));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 540, 10));

        Txt_Observaciones.setEditable(false);
        Txt_Observaciones.setBackground(new java.awt.Color(255, 255, 255));
        Txt_Observaciones.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Observaciones.setText("jTextField1");
        Txt_Observaciones.setBorder(null);
        Txt_Observaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_ObservacionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Txt_ObservacionesMouseEntered(evt);
            }
        });
        jPanel2.add(Txt_Observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 144, 540, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Datos básicos del paciente:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Nombre:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, -1));

        Txt_NomContacto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_NomContacto.setBorder(null);
        Txt_NomContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_NomContactoMouseClicked(evt);
            }
        });
        Txt_NomContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NomContactoActionPerformed(evt);
            }
        });
        Txt_NomContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_NomContactoKeyTyped(evt);
            }
        });
        jPanel2.add(Txt_NomContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 223, 150, 20));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 200, 10));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Nombre:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, -1));

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 200, 10));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Teléfono:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 80, -1));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 180, 10));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Teléfono:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 80, -1));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 220, 10));

        Txt_Especificacion3.setBorder(null);
        jPanel2.add(Txt_Especificacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 220, -1));

        Txt_Parentesco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Parentesco.setBorder(null);
        Txt_Parentesco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_ParentescoMouseClicked(evt);
            }
        });
        Txt_Parentesco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_ParentescoKeyTyped(evt);
            }
        });
        jPanel2.add(Txt_Parentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 223, 120, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("EN CASO DE EMERGENCIA CONTACTAR A:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 390, -1));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, 10));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 0, 255));
        jLabel16.setText("Presione el botón de descarga abajo para generar odontograma y periodontograma.");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1330, 620, 20));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel17.setText("¿Alguna vez ha estado gravemente enfermo?");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 300, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel18.setText("¿Ha sido intervenido quirurgicamente?");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 290, -1));

        buttonGroup3.add(RB3);
        RB3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB3.setText("SI");
        RB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB3ActionPerformed(evt);
            }
        });
        jPanel2.add(RB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, -1));

        jSeparator19.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 280, 10));

        buttonGroup3.add(RB33);
        RB33.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB33.setText("NO");
        RB33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB33ActionPerformed(evt);
            }
        });
        jPanel2.add(RB33, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        buttonGroup2.add(RB2);
        RB2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB2.setText("SI");
        RB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2ActionPerformed(evt);
            }
        });
        jPanel2.add(RB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        buttonGroup1.add(RB1);
        RB1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB1.setText("SI");
        RB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB1ActionPerformed(evt);
            }
        });
        jPanel2.add(RB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        buttonGroup1.add(RB11);
        RB11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB11.setText("NO");
        RB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB11ActionPerformed(evt);
            }
        });
        jPanel2.add(RB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        buttonGroup2.add(RB22);
        RB22.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB22.setText("NO");
        RB22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB22ActionPerformed(evt);
            }
        });
        jPanel2.add(RB22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Edad:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 70, -1));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, 10));

        jSeparator20.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator20.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 220, 10));

        jSeparator21.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator21.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 220, 10));

        Txt_TelContacto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_TelContacto.setBorder(null);
        Txt_TelContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Txt_TelContactoMouseClicked(evt);
            }
        });
        Txt_TelContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelContactoActionPerformed(evt);
            }
        });
        Txt_TelContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_TelContactoKeyTyped(evt);
            }
        });
        jPanel2.add(Txt_TelContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 223, 150, -1));

        Txt_Especificacion1.setBorder(null);
        jPanel2.add(Txt_Especificacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 220, -1));

        Txt_Especificacion2.setBorder(null);
        jPanel2.add(Txt_Especificacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 220, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel20.setText("¿Hay algún alimento que no pueda comer?");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 290, -1));

        buttonGroup4.add(RB4);
        RB4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB4.setText("SI");
        RB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB4ActionPerformed(evt);
            }
        });
        jPanel2.add(RB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));

        buttonGroup4.add(RB44);
        RB44.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB44.setText("NO");
        RB44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB44ActionPerformed(evt);
            }
        });
        jPanel2.add(RB44, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        Txt_Especificacion4.setBorder(null);
        jPanel2.add(Txt_Especificacion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 220, -1));

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 220, 10));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel22.setText("¿Hay algún medicamento o sustancia al que sea alérgico?");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 370, -1));

        buttonGroup5.add(RB5);
        RB5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB5.setText("SI");
        RB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB5ActionPerformed(evt);
            }
        });
        jPanel2.add(RB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, -1));

        buttonGroup5.add(RB55);
        RB55.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB55.setText("NO");
        RB55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB55ActionPerformed(evt);
            }
        });
        jPanel2.add(RB55, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        Txt_Especificacion5.setBorder(null);
        jPanel2.add(Txt_Especificacion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 220, -1));

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 220, 10));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel23.setText("¿Está embarazada o durante algún tratamiento hormonal?");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 370, -1));

        buttonGroup6.add(RB6);
        RB6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB6.setText("SI");
        RB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB6ActionPerformed(evt);
            }
        });
        jPanel2.add(RB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, -1));

        buttonGroup6.add(RB66);
        RB66.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB66.setText("NO");
        RB66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB66ActionPerformed(evt);
            }
        });
        jPanel2.add(RB66, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, -1));

        Txt_Especificacion6.setBorder(null);
        jPanel2.add(Txt_Especificacion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 220, -1));

        jSeparator22.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator22.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, 220, 10));

        jSeparator23.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator23.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 80, 10));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Hábitos:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 90, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel25.setText("¿Se encuentra bajo algún tratamiento médico?");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 290, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel26.setText("¿Fuma?");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 240, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel27.setText("¿Consume alcohol?");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 240, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel28.setText("¿Consume drogas?");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, 240, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel29.setText("¿Se muerde las uñas o los labios?");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, 230, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel30.setText("¿Ha recibido alguno de los siguientes tratamientos odontológicos?");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1030, 500, -1));

        Txt_Habito.setBorder(null);
        jPanel2.add(Txt_Habito, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 810, 130, -1));

        buttonGroup7.add(RB7);
        RB7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB7.setText("SI");
        RB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB7ActionPerformed(evt);
            }
        });
        jPanel2.add(RB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, -1, -1));

        buttonGroup7.add(RB77);
        RB77.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB77.setText("NO");
        RB77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB77ActionPerformed(evt);
            }
        });
        jPanel2.add(RB77, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, -1, -1));

        buttonGroup8.add(RB8);
        RB8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB8.setText("SI");
        RB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB8ActionPerformed(evt);
            }
        });
        jPanel2.add(RB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 680, -1, -1));

        buttonGroup8.add(RB88);
        RB88.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB88.setText("NO");
        RB88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB88ActionPerformed(evt);
            }
        });
        jPanel2.add(RB88, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, -1, -1));

        buttonGroup9.add(RB9);
        RB9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB9.setText("SI");
        RB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB9ActionPerformed(evt);
            }
        });
        jPanel2.add(RB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 710, -1, -1));

        buttonGroup9.add(RB99);
        RB99.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RB99.setText("NO");
        RB99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB99ActionPerformed(evt);
            }
        });
        jPanel2.add(RB99, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, -1, -1));

        buttonGroup10.add(RBA);
        RBA.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RBA.setText("SI");
        RBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBAActionPerformed(evt);
            }
        });
        jPanel2.add(RBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 740, -1, -1));

        buttonGroup10.add(RBAA);
        RBAA.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RBAA.setText("NO");
        RBAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBAAActionPerformed(evt);
            }
        });
        jPanel2.add(RBAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 740, -1, -1));

        buttonGroup11.add(RBB);
        RBB.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RBB.setText("SI");
        RBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBActionPerformed(evt);
            }
        });
        jPanel2.add(RBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 770, -1, -1));

        buttonGroup11.add(RBBB);
        RBBB.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        RBBB.setText("NO");
        RBBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBBActionPerformed(evt);
            }
        });
        jPanel2.add(RBBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 770, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setText("HISTORIA ODONTOLÓGICA");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 880, 260, -1));

        jSeparator25.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator25.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1190, 290, 10));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel32.setText("?");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 990, 40, -1));

        jSeparator26.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator26.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 830, 130, 10));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel33.setText("¿Otro?  Especifique:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 800, 230, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel34.setText("¿Presenta dolores en: boca");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 990, 170, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel35.setText("cara");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 990, 30, -1));
        jPanel2.add(Check_Restauracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 1110, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel36.setText("Endodoncia");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1070, 80, -1));
        jPanel2.add(Check_cuello, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 990, -1, -1));
        jPanel2.add(Check_cara, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 990, -1, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel37.setText("¿Abre cosas con los dientes?");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, 230, -1));

        Txt_Motivo.setBorder(null);
        jPanel2.add(Txt_Motivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 940, 590, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel38.setText("cuello");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 990, 40, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel39.setText("Ortodoncia");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1070, 80, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel40.setText("Cirugía maxilofacial");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1110, 130, -1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel41.setText("Implantes dentales");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1110, 120, -1));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel42.setText("Restauración oral");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1110, 120, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel43.setText("Periodoncia");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1070, 80, -1));
        jPanel2.add(Check_boca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 990, -1, -1));
        jPanel2.add(Check_Ortodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1070, -1, -1));
        jPanel2.add(Check_Cirugia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1110, -1, -1));
        jPanel2.add(Check_Periodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1070, -1, -1));
        jPanel2.add(Check_Implantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1110, -1, -1));
        jPanel2.add(Check_Endodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1070, -1, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel44.setText("Motivo de la consulta:");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 940, 140, -1));

        jSeparator28.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator28.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 960, 590, 10));

        jSeparator29.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator29.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 900, 250, 10));

        jScrollPane2.setViewportView(Txt_Otras_Obs);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1210, 730, 90));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel45.setText("OBSERVACIONES DE CITAS PREVIAS");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1170, 290, -1));
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1340, 500, -1));

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("---------------------------------------------------------------------------------------------");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1340, 500, 40));

        Txt_Error_Tel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Error_Tel.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(Txt_Error_Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 230, 20));

        Txt_Error_Nom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Error_Nom.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(Txt_Error_Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 20));

        Txt_Error_Par.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Txt_Error_Par.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(Txt_Error_Par, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 220, 20));

        jScrollPane1.setViewportView(jPanel2);

        panelRound2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 820, 460));

        GuardarHistoria.setBackground(new java.awt.Color(0, 0, 102));
        GuardarHistoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GuardarHistoria.setForeground(new java.awt.Color(255, 255, 255));
        GuardarHistoria.setText("Guardar Historia");
        GuardarHistoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GuardarHistoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardarHistoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuardarHistoriaMouseExited(evt);
            }
        });
        GuardarHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarHistoriaActionPerformed(evt);
            }
        });
        panelRound2.add(GuardarHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 260, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseClicked
        Txt_Error.setText("");
    }//GEN-LAST:event_panelRound2MouseClicked

    private void DescargarDiagramasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargarDiagramasActionPerformed

        control.DescargarDiagramasPaciente();
        
    }//GEN-LAST:event_DescargarDiagramasActionPerformed

    private void DescargarDiagramasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescargarDiagramasMouseExited
        DescargarDiagramas.setBackground(new Color(153,51,255));
    }//GEN-LAST:event_DescargarDiagramasMouseExited

    private void DescargarDiagramasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescargarDiagramasMouseEntered
        DescargarDiagramas.setBackground(new Color(204,153,255));
    }//GEN-LAST:event_DescargarDiagramasMouseEntered

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        GestionPacientes1 destino = new GestionPacientes1(cedula_update);
        control.ConectarPanel(this, destino,  960, 639, 0, 0);
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void Txt_NombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_NombreMouseClicked
        Txt_Error.setText(MENSAJE);
    }//GEN-LAST:event_Txt_NombreMouseClicked

    private void Txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreActionPerformed

    private void Txt_NomContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_NomContactoMouseClicked
      Txt_Error_Nom.setText("");        
    }//GEN-LAST:event_Txt_NomContactoMouseClicked

    private void Txt_NomContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NomContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NomContactoActionPerformed

    private void RB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB3ActionPerformed

    private void RB33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB33ActionPerformed

    private void RB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB2ActionPerformed

    private void RB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB1ActionPerformed

    private void RB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB11ActionPerformed

    private void RB22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB22ActionPerformed

    private void RB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB4ActionPerformed

    private void RB44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB44ActionPerformed

    private void RB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB5ActionPerformed

    private void RB55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB55ActionPerformed

    private void RB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB6ActionPerformed

    private void RB66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB66ActionPerformed

    private void RB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB7ActionPerformed

    private void RB77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB77ActionPerformed

    private void RB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB8ActionPerformed

    private void RB88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB88ActionPerformed

    private void RB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB9ActionPerformed

    private void RB99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB99ActionPerformed

    private void RBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBAActionPerformed

    private void RBAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBAAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBAAActionPerformed

    private void RBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBBActionPerformed

    private void RBBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBBBActionPerformed

    private void GuardarHistoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarHistoriaMouseEntered
        GuardarHistoria.setBackground(new Color(4,119,255));
    }//GEN-LAST:event_GuardarHistoriaMouseEntered

    private void GuardarHistoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarHistoriaMouseExited
        GuardarHistoria.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_GuardarHistoriaMouseExited

    private void GuardarHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarHistoriaActionPerformed

        control.Registrar_GuardarHistoria();
        
    }//GEN-LAST:event_GuardarHistoriaActionPerformed

    private void Txt_TelContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelContactoActionPerformed

    private void Txt_CedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_CedulaMouseClicked
        Txt_Error.setText(MENSAJE);
    }//GEN-LAST:event_Txt_CedulaMouseClicked

    private void Txt_EdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_EdadMouseClicked
        Txt_Error.setText(MENSAJE);
    }//GEN-LAST:event_Txt_EdadMouseClicked

    private void Txt_SexoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_SexoMouseClicked
        Txt_Error.setText(MENSAJE);
    }//GEN-LAST:event_Txt_SexoMouseClicked

    private void Txt_TelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_TelefonoMouseClicked
        Txt_Error.setText(MENSAJE);
    }//GEN-LAST:event_Txt_TelefonoMouseClicked

    private void Txt_DireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_DireccionMouseClicked
        Txt_Error.setText(MENSAJE);
    }//GEN-LAST:event_Txt_DireccionMouseClicked

    private void Txt_ObservacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_ObservacionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ObservacionesMouseEntered

    private void Txt_ObservacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_ObservacionesMouseClicked
        Txt_Error.setText(MENSAJE);
    }//GEN-LAST:event_Txt_ObservacionesMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Txt_Error.setText("");
    }//GEN-LAST:event_jPanel1MouseClicked

    private void panelRound1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound1MouseClicked
        Txt_Error.setText("");
    }//GEN-LAST:event_panelRound1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        Txt_Error.setText("");
    }//GEN-LAST:event_jPanel2MouseClicked

    private void Txt_NomContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NomContactoKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){
        
            Txt_Error_Nom.setText("Ingrese solo letras");
           
            evt.consume();
        }
    }//GEN-LAST:event_Txt_NomContactoKeyTyped

    private void Txt_TelContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_TelContactoKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros){
            Txt_Error_Tel.setText("Ingrese solo números");
            evt.consume();
        }    
        if (Txt_TelContacto.getText().trim().length() >=11) {
            evt.consume();
        }
    }//GEN-LAST:event_Txt_TelContactoKeyTyped

    private void Txt_TelContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_TelContactoMouseClicked
        Txt_Error_Tel.setText("");
    }//GEN-LAST:event_Txt_TelContactoMouseClicked

    private void Txt_ParentescoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_ParentescoKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){
        
            Txt_Error_Par.setText("Ingrese solo letras");
           
            evt.consume();
        }
    }//GEN-LAST:event_Txt_ParentescoKeyTyped

    private void Txt_ParentescoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_ParentescoMouseClicked
        Txt_Error_Par.setText("");
    }//GEN-LAST:event_Txt_ParentescoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro CerrarSesion;
    private javax.swing.JCheckBox Check_Cirugia;
    private javax.swing.JCheckBox Check_Endodoncia;
    private javax.swing.JCheckBox Check_Implantes;
    private javax.swing.JCheckBox Check_Ortodoncia;
    private javax.swing.JCheckBox Check_Periodoncia;
    private javax.swing.JCheckBox Check_Restauracion;
    private javax.swing.JCheckBox Check_boca;
    private javax.swing.JCheckBox Check_cara;
    private javax.swing.JCheckBox Check_cuello;
    private javax.swing.JButton DescargarDiagramas;
    private javax.swing.JButton GuardarHistoria;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB11;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB22;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB33;
    private javax.swing.JRadioButton RB4;
    private javax.swing.JRadioButton RB44;
    private javax.swing.JRadioButton RB5;
    private javax.swing.JRadioButton RB55;
    private javax.swing.JRadioButton RB6;
    private javax.swing.JRadioButton RB66;
    private javax.swing.JRadioButton RB7;
    private javax.swing.JRadioButton RB77;
    private javax.swing.JRadioButton RB8;
    private javax.swing.JRadioButton RB88;
    private javax.swing.JRadioButton RB9;
    private javax.swing.JRadioButton RB99;
    private javax.swing.JRadioButton RBA;
    private javax.swing.JRadioButton RBAA;
    private javax.swing.JRadioButton RBB;
    private javax.swing.JRadioButton RBBB;
    private javax.swing.JTextField Txt_Cedula;
    private javax.swing.JTextField Txt_Direccion;
    private javax.swing.JTextField Txt_Edad;
    private javax.swing.JLabel Txt_Error;
    private javax.swing.JLabel Txt_Error_Nom;
    private javax.swing.JLabel Txt_Error_Par;
    private javax.swing.JLabel Txt_Error_Tel;
    private javax.swing.JTextField Txt_Especificacion1;
    private javax.swing.JTextField Txt_Especificacion2;
    private javax.swing.JTextField Txt_Especificacion3;
    private javax.swing.JTextField Txt_Especificacion4;
    private javax.swing.JTextField Txt_Especificacion5;
    private javax.swing.JTextField Txt_Especificacion6;
    private javax.swing.JTextField Txt_Habito;
    private javax.swing.JTextField Txt_Motivo;
    private javax.swing.JTextField Txt_NomContacto;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_Observaciones;
    private javax.swing.JTextPane Txt_Otras_Obs;
    private javax.swing.JTextField Txt_Parentesco;
    private javax.swing.JTextField Txt_Sexo;
    private javax.swing.JTextField Txt_TelContacto;
    private javax.swing.JTextField Txt_Telefono;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private Modelo.PanelRound panelRound1;
    private Modelo.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
