/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.GCitas;

import Controlador.ControladorGCita;

import Modelo.Conexion;


import java.awt.Color;

import java.sql.Connection;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class GestionCitas extends javax.swing.JPanel {

    ControladorGCita control;
///////////////////////
 String CeduNom;
 String Cedu;
 String Nom;
 String nombre;  
////////////////
   
    

    /**
     * Creates new form GestionOdontologos1
     */
    public GestionCitas() {
        initComponents();
        control = new ControladorGCita(TablaOdontologos);
        control.LLenarTablaOdontologo();
    }

    public GestionCitas(String CeduNom) {
        this.CeduNom=CeduNom;
        String Cedul[]= CeduNom.split("-");
        initComponents();
        control = new ControladorGCita(TablaOdontologos);
        control.LLenarTablaOdontologo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelRound15 = new Modelo.PanelRound();
        BuscarTodo = new javax.swing.JTextField();
        jScrollPaneO = new javax.swing.JScrollPane();
        TablaOdontologos = new javax.swing.JTable();
        BModi = new javax.swing.JButton();
        panelRound2 = new Modelo.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new Modelo.PanelRound();
        jLabel12 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelRound15.setBackground(new java.awt.Color(162, 215, 239));
        panelRound15.setRoundBottomLeft(50);
        panelRound15.setRoundBottomRight(50);
        panelRound15.setRoundTopLeft(50);
        panelRound15.setRoundTopRight(50);

        BuscarTodo.setBackground(new java.awt.Color(204, 204, 204));
        BuscarTodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BuscarTodo.setForeground(new java.awt.Color(255, 255, 255));
        BuscarTodo.setText("Ingrese datos del odontólogo...");
        BuscarTodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BuscarTodoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BuscarTodoFocusLost(evt);
            }
        });
        BuscarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarTodoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarTodoMouseExited(evt);
            }
        });
        BuscarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTodoActionPerformed(evt);
            }
        });
        BuscarTodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarTodoKeyPressed(evt);
            }
        });

        TablaOdontologos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneO.setViewportView(TablaOdontologos);

        BModi.setBackground(new java.awt.Color(0, 0, 102));
        BModi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BModi.setForeground(new java.awt.Color(255, 255, 255));
        BModi.setText("Consultar");
        BModi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BModi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BModiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BModiMouseExited(evt);
            }
        });
        BModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModiActionPerformed(evt);
            }
        });

        panelRound2.setBackground(new java.awt.Color(88, 234, 253));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de Odontólogos registrados");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel2)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPaneO, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BModi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRound15Layout.createSequentialGroup()
                            .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BuscarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneO, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BModi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(957, 957, 957))
        );

        panelRound1.setBackground(new java.awt.Color(162, 215, 239));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GESTIÓN DE CITAS");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound15, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarTodoActionPerformed

    private void BuscarTodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarTodoKeyPressed

        String[] columna = {"Nombre", "Cedula", "Telefono", "Correo", "Usuario", "Clave", "F. Ingreso", "Especialidad"}; // se modifico
        String[] registros = new String[8];
           TablaOdontologos.getTableHeader().setReorderingAllowed(false);
        DefaultTableModel dtm = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String ssql = "SELECT *FROM odontologos WHERE Nombre LIKE '%" + BuscarTodo.getText() + "%' "
                + "OR Cedula LIKE '%" + BuscarTodo.getText() + "%'"
                + "OR Correo LIKE '%" + BuscarTodo.getText() + "%'"
                + "OR Telefono LIKE '%" + BuscarTodo.getText() + "%'"
                + "OR Especialidad LIKE '%" + BuscarTodo.getText() + "%'";
        try {
            Connection cn = Conexion.conectarBD();
            Statement stm = (Statement) cn.createStatement();
            ResultSet res = stm.executeQuery(ssql);

            while (res.next()) {

                registros[0] = res.getString(1); //nombre
                registros[1] = res.getString(2); //cedula
                registros[2] = res.getString(4); //telefono
                registros[3] = res.getString(5); //correo               
                registros[4] = res.getString(7); //user
                registros[5] = res.getString(8); // clave
                registros[6] = res.getString(9); // Fecha Ingreso
                registros[7] = res.getString(10); //especialidad

                dtm.addRow(registros);
            }
            TablaOdontologos.setModel(dtm);
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al ingresarlo en la BD " + e);
            JOptionPane.showMessageDialog(null, "¡Contacte al administrador!");
        }
    }//GEN-LAST:event_BuscarTodoKeyPressed

    
    
    
    private void BModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModiActionPerformed
         
    int fila=TablaOdontologos.getSelectedRow(); //llamar tabla odontologo
    if (fila>-1) {
        String Cedula= TablaOdontologos.getValueAt(fila, 1).toString().trim();
        String Nombre=TablaOdontologos.getValueAt(fila, 0).toString().trim();
        VerCitas destino = new VerCitas(Nombre, CeduNom, Cedula);
        control.ConectarPanel(jPanel2, destino,  960, 639, 0, 0);  
       
    }else{
        JOptionPane.showMessageDialog(null, "Debe seleccionar un odontólogo antes de consultar");
    }
      
    }//GEN-LAST:event_BModiActionPerformed

    private void BModiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BModiMouseEntered
        BModi.setBackground(new Color(4,119,255));
    }//GEN-LAST:event_BModiMouseEntered

    private void BModiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BModiMouseExited
         BModi.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_BModiMouseExited

    private void BuscarTodoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarTodoFocusGained
        
        if(BuscarTodo.getText().equals("Ingrese datos del odontólogo...")){
            BuscarTodo.setText("");
            
        }
        
        BuscarTodo.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BuscarTodoFocusGained

    private void BuscarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarTodoMouseClicked
        BuscarTodo.setBackground(new Color(255,255,255));
        BuscarTodo.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_BuscarTodoMouseClicked

    private void BuscarTodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarTodoMouseExited
        
    }//GEN-LAST:event_BuscarTodoMouseExited

    private void BuscarTodoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarTodoFocusLost
        if(BuscarTodo.getText().trim().equals("") ){
            BuscarTodo.setText("Ingrese datos del odontólogo...");
            
        }
        
        BuscarTodo.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BuscarTodoFocusLost
 
    
    /*public void PlaceHolder(){
        JPlaceHolderTextField up = new JPlaceHolderTextField("Escriba",BuscarTodo);
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BModi;
    private javax.swing.JTextField BuscarTodo;
    private javax.swing.JTable TablaOdontologos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneO;
    private Modelo.PanelRound panelRound1;
    private Modelo.PanelRound panelRound15;
    private Modelo.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
