
package Vista.GCitas;

import Controlador.ControladorGCita;
import Modelo.Conexion;
import java.awt.Color;

import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;



/**
 *
 * @author andre
 */
public class RegistrarCita extends javax.swing.JPanel {
    String CeduCar;
    String nombre;
    String cedula;
    String Doc_Cedula;
    String Car;
    ControladorGCita control;
    public RegistrarCita(String nombre,String CeduCar, String Doc_Cedula) {
        this.CeduCar=CeduCar;
        this.nombre=nombre;
        this.Doc_Cedula=Doc_Cedula;
        String Cedul[]= CeduCar.split("-");
        this.Car=Cedul[1];
        this.cedula=Cedul[0];
        initComponents();
        control= new ControladorGCita(TextNombre,  TextCedula, TextDireccion, TextTelefono,TextDescripcion,  TextServicio,  Error_Fecha, Error_Cedula,  Error_Telefono,  ListTel,  Fecha, TablaP, TablaC,Error_Fecha);
        control.LLenarTablaPacientes();
        control.LLenarTablaServicios();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelRound2 = new Modelo.PanelRound();
        panelRound1 = new Modelo.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        panelRound3 = new Modelo.PanelRound();
        panelRound4 = new Modelo.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        TextDireccion = new javax.swing.JTextField();
        TextTelefono = new javax.swing.JTextField();
        TextCedula = new javax.swing.JTextField();
        TextNombre = new javax.swing.JTextField();
        TextServicio = new javax.swing.JTextField();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        Error_Fecha = new javax.swing.JTextField();
        Error_Cedula = new javax.swing.JTextField();
        Error_Direccion = new javax.swing.JTextField();
        Error_Telefono = new javax.swing.JTextField();
        ListTel = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Seleccionar2 = new rsbuttom.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaP = new javax.swing.JTable();
        Regresar = new rsbuttom.RSButtonMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaC = new javax.swing.JTable();
        Seleccionar1 = new rsbuttom.RSButtonMetro();
        BuscarTodoP = new javax.swing.JTextField();
        BuscarTodoC = new javax.swing.JTextField();
        Fecha = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        TextDescripcion = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Error_Nombre1 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1005, 649));

        panelRound2.setBackground(new java.awt.Color(204, 204, 204));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        panelRound1.setBackground(new java.awt.Color(242, 217, 217));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("REGISTRAR CITA");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(242, 217, 217));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(174, 202, 229));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos de la Cita");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound3.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 900, 50));

        TextDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDireccionActionPerformed(evt);
            }
        });
        TextDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextDireccionKeyTyped(evt);
            }
        });
        panelRound3.add(TextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 230, 31));

        TextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoActionPerformed(evt);
            }
        });
        TextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextTelefonoKeyTyped(evt);
            }
        });
        panelRound3.add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 140, 31));

        TextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCedulaActionPerformed(evt);
            }
        });
        TextCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextCedulaKeyTyped(evt);
            }
        });
        panelRound3.add(TextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 190, 31));

        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        TextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextNombreKeyTyped(evt);
            }
        });
        panelRound3.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 240, 31));

        TextServicio.setText("NULL");
        TextServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextServicioActionPerformed(evt);
            }
        });
        panelRound3.add(TextServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, 30));

        rSButtonMetro2.setText("Agregar");
        rSButtonMetro2.setColorHover(new java.awt.Color(104, 255, 104));
        rSButtonMetro2.setColorNormal(new java.awt.Color(113, 226, 113));
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });
        panelRound3.add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 202, 45));

        Error_Fecha.setEditable(false);
        Error_Fecha.setBackground(new java.awt.Color(0,0,0,1));
        Error_Fecha.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Fecha.setForeground(new java.awt.Color(255, 0, 0));
        Error_Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Fecha.setBorder(null);
        panelRound3.add(Error_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 20));

        Error_Cedula.setEditable(false);
        Error_Cedula.setBackground(new java.awt.Color(0,0,0,1));
        Error_Cedula.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Cedula.setForeground(new java.awt.Color(255, 0, 0));
        Error_Cedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Cedula.setBorder(null);
        Error_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_CedulaActionPerformed(evt);
            }
        });
        panelRound3.add(Error_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 180, 30));

        Error_Direccion.setEditable(false);
        Error_Direccion.setBackground(new java.awt.Color(0,0,0,1));
        Error_Direccion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Direccion.setForeground(new java.awt.Color(255, 0, 0));
        Error_Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Direccion.setBorder(null);
        panelRound3.add(Error_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 190, 20));

        Error_Telefono.setEditable(false);
        Error_Telefono.setBackground(new java.awt.Color(0,0,0,1));
        Error_Telefono.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Telefono.setForeground(new java.awt.Color(255, 0, 0));
        Error_Telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Telefono.setBorder(null);
        Error_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Error_TelefonoActionPerformed(evt);
            }
        });
        panelRound3.add(Error_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 240, 20));

        ListTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "0212", "0412", "0414", "0424", "0416", "0426" }));
        ListTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListTelActionPerformed(evt);
            }
        });
        panelRound3.add(ListTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 90, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Cédula");
        panelRound3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Dirección");
        panelRound3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Teléfono");
        panelRound3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Servicio");
        panelRound3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        Seleccionar2.setText("Seleccionar");
        Seleccionar2.setColorHover(new java.awt.Color(102, 204, 255));
        Seleccionar2.setColorNormal(new java.awt.Color(153, 255, 204));
        Seleccionar2.setColorTextNormal(new java.awt.Color(0, 0, 0));
        Seleccionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccionar2ActionPerformed(evt);
            }
        });
        panelRound3.add(Seleccionar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 90, 30));

        TablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaP);

        panelRound3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 360, 110));

        Regresar.setText("Regresar");
        Regresar.setColorHover(new java.awt.Color(102, 204, 255));
        Regresar.setColorNormal(new java.awt.Color(153, 255, 204));
        Regresar.setColorTextNormal(new java.awt.Color(0, 0, 0));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        panelRound3.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 130, -1));

        TablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(TablaC);

        panelRound3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 370, 110));

        Seleccionar1.setText("Seleccionar");
        Seleccionar1.setColorHover(new java.awt.Color(102, 204, 255));
        Seleccionar1.setColorNormal(new java.awt.Color(153, 255, 204));
        Seleccionar1.setColorTextNormal(new java.awt.Color(0, 0, 0));
        Seleccionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccionar1ActionPerformed(evt);
            }
        });
        panelRound3.add(Seleccionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 90, 30));

        BuscarTodoP.setBackground(new java.awt.Color(204, 204, 204));
        BuscarTodoP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BuscarTodoP.setForeground(new java.awt.Color(255, 255, 255));
        BuscarTodoP.setText("Ingrese datos del paciente...");
        BuscarTodoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BuscarTodoPFocusGained(evt);
            }
        });
        BuscarTodoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTodoPActionPerformed(evt);
            }
        });
        BuscarTodoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarTodoPKeyPressed(evt);
            }
        });
        panelRound3.add(BuscarTodoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        BuscarTodoC.setBackground(new java.awt.Color(204, 204, 204));
        BuscarTodoC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BuscarTodoC.setForeground(new java.awt.Color(255, 255, 255));
        BuscarTodoC.setText("Ingrese datos del servicio...");
        BuscarTodoC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BuscarTodoCFocusGained(evt);
            }
        });
        BuscarTodoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTodoCActionPerformed(evt);
            }
        });
        BuscarTodoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarTodoCKeyPressed(evt);
            }
        });
        panelRound3.add(BuscarTodoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 200, -1));

        Fecha.setDateFormatString("dd-MM-yyyy");
        panelRound3.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Nombre Completo");
        panelRound3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Fecha");
        panelRound3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        TextDescripcion.setText("NULL");
        TextDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDescripcionActionPerformed(evt);
            }
        });
        panelRound3.add(TextDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 430, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Descripción");
        panelRound3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        Error_Nombre1.setEditable(false);
        Error_Nombre1.setBackground(new java.awt.Color(0,0,0,1));
        Error_Nombre1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Error_Nombre1.setForeground(new java.awt.Color(255, 0, 0));
        Error_Nombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Error_Nombre1.setBorder(null);
        panelRound3.add(Error_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 240, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(panelRound3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoActionPerformed

    private void TextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCedulaActionPerformed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void TextServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextServicioActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        if ("Secretaria".equals(Car)) {
            try {
                if(control.Registrarcita(Doc_Cedula)){
                    VerCitas destino = new VerCitas(nombre,CeduCar,Doc_Cedula);
                    control.ConectarPanel(this, destino, 960, 639, 1, 0);
                }
            } catch (ParseException ex) {
                Logger.getLogger(RegistrarCita.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                if(control.Registrarcita( cedula)){
                    VerCitas destino = new VerCitas(nombre,CeduCar,Doc_Cedula);
                    control.ConectarPanel(this, destino, 960, 639, 1, 0);
                }
            } catch (ParseException ex) {
                Logger.getLogger(RegistrarCita.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void TextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextNombreKeyTyped
         int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)){
        
            Error_Fecha.setText("No se aceptan caracteres especiales ni números");
           
           
            evt.consume();
        }
    }//GEN-LAST:event_TextNombreKeyTyped

    private void TextCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextCedulaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros)
        {
            Error_Cedula.setText("No se aceptan caracteres especiales ni letras");
           
            evt.consume();
        }
        if (TextCedula.getText().trim().length() >=8) {
            
            Error_Cedula.setText("La cédula debe tener 6-8 dígitos");
          
            evt.consume();
        }
    }//GEN-LAST:event_TextCedulaKeyTyped

    private void TextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextTelefonoKeyTyped
         int key = evt.getKeyChar();

        boolean numeros = (key >= 48 && key <= 57) || key==127 || key==8;

        if (!numeros){
            Error_Telefono.setText("No se aceptan caracteres especiales ni letras");
            evt.consume();
        }
        if (TextTelefono.getText().trim().length() >=7) {
            
            Error_Telefono.setText("Seleccione e ingrese los últimos 7 dígitos");
            evt.consume();
        }
    }//GEN-LAST:event_TextTelefonoKeyTyped

    private void ListTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListTelActionPerformed

    private void Seleccionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccionar2ActionPerformed
        control.SeleccionarServicio();
    }//GEN-LAST:event_Seleccionar2ActionPerformed

    private void TextDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextDireccionKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = (key >= 97 && key <= 122) || key==127 || key==8;
        boolean espacio = key == 32;
        boolean numeros= (key >= 48 && key <= 57);
        if (!(minusculas || mayusculas || espacio || numeros)){

            Error_Direccion.setText("No se aceptan caracteres especiales.");

            evt.consume();
        }
    }//GEN-LAST:event_TextDireccionKeyTyped

    private void TextDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDireccionActionPerformed

    private void Error_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_CedulaActionPerformed

    private void Error_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Error_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Error_TelefonoActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
       VerCitas destino = new VerCitas(nombre,CeduCar,Doc_Cedula );
        control.ConectarPanel(this, destino, 960, 639, 1, 0);
    }//GEN-LAST:event_RegresarActionPerformed

    private void Seleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccionar1ActionPerformed
        control.SeleccionarPaciente();

    }//GEN-LAST:event_Seleccionar1ActionPerformed

    private void BuscarTodoPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarTodoPFocusGained
        if(BuscarTodoP.getText().equals("Ingrese datos del paciente...")){
            BuscarTodoP.setText("");

        }

        BuscarTodoP.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BuscarTodoPFocusGained

    private void BuscarTodoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTodoPActionPerformed

    }//GEN-LAST:event_BuscarTodoPActionPerformed

    private void BuscarTodoPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarTodoPKeyPressed

        String[] columna = {"Nombre","Cedula", "Direccion", "Telefono" };
        String[] registros = new String[4];
        TablaP.getTableHeader().setReorderingAllowed(false);
        DefaultTableModel dtm = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String ssql = "SELECT * FROM pacientes WHERE Nombre LIKE '%" + BuscarTodoP.getText() + "%' "
        + "OR Cedula LIKE '%" + BuscarTodoP.getText() + "%'"
        + "OR Direccion LIKE '%" + BuscarTodoP.getText() + "%'"
        + "OR Telefono LIKE '%" + BuscarTodoP.getText() + "%'";
        try {
            Connection cn = Conexion.conectarBD();
            Statement stm = (Statement) cn.createStatement();
            ResultSet res = stm.executeQuery(ssql);

            while (res.next()) {

                registros[0] = res.getString(1); //nombre
                registros[1] = res.getString(2); //cedula
                registros[2] = res.getString(3); //direccion
                registros[3] = res.getString(4); //telefono

                dtm.addRow(registros);
            }
            TablaP.setModel(dtm);
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al filtrar desde la BD " + e);
            JOptionPane.showMessageDialog(null, "¡Contacte al administrador!");
        }
    }//GEN-LAST:event_BuscarTodoPKeyPressed

    private void BuscarTodoCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarTodoCFocusGained
        if(BuscarTodoC.getText().equals("Ingrese datos del servicio...")){
            BuscarTodoC.setText("");

        }

        BuscarTodoC.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BuscarTodoCFocusGained

    private void BuscarTodoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTodoCActionPerformed

    }//GEN-LAST:event_BuscarTodoCActionPerformed

    private void BuscarTodoCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarTodoCKeyPressed

        String[] columna = {"Nombre", "Descripcion"};
        String[] registros = new String[2];
        TablaC.getTableHeader().setReorderingAllowed(false);
        DefaultTableModel dtm = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String ssql = "SELECT * FROM servicios WHERE Nombre LIKE '%" + BuscarTodoC.getText() + "%' "
        + "OR Descripcion LIKE '%" + BuscarTodoC.getText() + "%'";
        try {
            Connection cn = Conexion.conectarBD();
            Statement stm = (Statement) cn.createStatement();
            ResultSet res = stm.executeQuery(ssql);

            while (res.next()) {

                registros[0] = res.getString(1); //nombre
                registros[1] = res.getString(3); //descripcion

                dtm.addRow(registros);
            }
            TablaC.setModel(dtm);
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al filtrar desde la BD " + e);
            JOptionPane.showMessageDialog(null, "¡Contacte al administrador!");
        }
    }//GEN-LAST:event_BuscarTodoCKeyPressed

    private void TextDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDescripcionActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarTodoC;
    private javax.swing.JTextField BuscarTodoP;
    private javax.swing.JTextField Error_Cedula;
    private javax.swing.JTextField Error_Direccion;
    private javax.swing.JTextField Error_Fecha;
    private javax.swing.JTextField Error_Nombre1;
    private javax.swing.JTextField Error_Telefono;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JComboBox<String> ListTel;
    private rsbuttom.RSButtonMetro Regresar;
    private rsbuttom.RSButtonMetro Seleccionar1;
    private rsbuttom.RSButtonMetro Seleccionar2;
    private javax.swing.JTable TablaC;
    private javax.swing.JTable TablaP;
    private javax.swing.JTextField TextCedula;
    private javax.swing.JTextField TextDescripcion;
    private javax.swing.JTextField TextDireccion;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextServicio;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Modelo.PanelRound panelRound1;
    private Modelo.PanelRound panelRound2;
    private Modelo.PanelRound panelRound3;
    private Modelo.PanelRound panelRound4;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    // End of variables declaration//GEN-END:variables
}
