
package Vista.GCitas;

import Controlador.ControladorGCita;
import Modelo.Conexion;
import java.awt.Color;

import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;



public class VerCitas extends javax.swing.JPanel {
String CeduCar;
String nombre;
String Doc_Selec;
String Car;
String Cedula_Usuario;
    ControladorGCita control;
    public VerCitas(String nombre, String CeduCar, String Ced_DocSelec) {
        this.CeduCar=CeduCar;
        this.nombre=nombre;
        String Cedul[]= CeduCar.split("-");
        this.Car=Cedul[1];
        Cedula_Usuario=Cedul[0];
        initComponents();
        Doc_Selec=Ced_DocSelec;
        NombreOdo.setText(nombre);
        control= new ControladorGCita(TablaCitas,null);
        if ("Secretaria".equals(Car)) {
            control.LLenarTablaCitas(Doc_Selec);
        } else {
            control.LLenarTablaCitas(Cedula_Usuario);
            Regresar.setText("");
            Regresar.setBorderPainted(false);
            Regresar.setContentAreaFilled(false);
            Regresar.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelRound1 = new Modelo.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        NombreOdo = new javax.swing.JLabel();
        panelRound3 = new Modelo.PanelRound();
        panelRound4 = new Modelo.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        Agregar = new rsbuttom.RSButtonMetro();
        Regresar = new rsbuttom.RSButtonMetro();
        BConsultar = new javax.swing.JButton();
        jScrollPaneO = new javax.swing.JScrollPane();
        TablaCitas = new javax.swing.JTable();
        BuscarTodoP = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1005, 649));

        panelRound1.setBackground(new java.awt.Color(162, 215, 239));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CITAS DE:");

        NombreOdo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        NombreOdo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel12)
                .addGap(39, 39, 39)
                .addComponent(NombreOdo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreOdo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(162, 215, 239));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(0, 0, 204));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Citas");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound3.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 900, 50));

        Agregar.setText("Agregar");
        Agregar.setColorHover(new java.awt.Color(104, 255, 104));
        Agregar.setColorNormal(new java.awt.Color(113, 226, 113));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        panelRound3.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 40));

        Regresar.setText("Regresar");
        Regresar.setColorHover(new java.awt.Color(102, 204, 255));
        Regresar.setColorNormal(new java.awt.Color(153, 255, 204));
        Regresar.setColorTextNormal(new java.awt.Color(0, 0, 0));
        Regresar.setContentAreaFilled(true);
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        panelRound3.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 130, -1));

        BConsultar.setBackground(new java.awt.Color(0, 0, 102));
        BConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BConsultar.setForeground(new java.awt.Color(255, 255, 255));
        BConsultar.setText("Consultar");
        BConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BConsultarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BConsultarMouseExited(evt);
            }
        });
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });
        panelRound3.add(BConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 150, 40));

        TablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaCitas.setAutoscrolls(false);
        jScrollPaneO.setViewportView(TablaCitas);

        panelRound3.add(jScrollPaneO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 730, 280));

        BuscarTodoP.setBackground(new java.awt.Color(204, 204, 204));
        BuscarTodoP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BuscarTodoP.setForeground(new java.awt.Color(255, 255, 255));
        BuscarTodoP.setText("Ingrese datos de la cita...");
        BuscarTodoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BuscarTodoPFocusGained(evt);
            }
        });
        BuscarTodoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTodoPActionPerformed(evt);
            }
        });
        BuscarTodoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarTodoPKeyPressed(evt);
            }
        });
        panelRound3.add(BuscarTodoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 210, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        if ("Secretaria".equals(Car)) {
            GestionCitas destino = new GestionCitas(CeduCar);
            control.ConectarPanel(this, destino, 960, 639, 1, 0);
        } 
        
       
    }//GEN-LAST:event_RegresarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        RegistrarCita destino = new RegistrarCita(nombre,CeduCar,Doc_Selec );
        control.ConectarPanel(this, destino, 960, 639, 1, 0);
    }//GEN-LAST:event_AgregarActionPerformed

    private void BConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BConsultarMouseEntered
        BConsultar.setBackground(new Color(4,119,255));
    }//GEN-LAST:event_BConsultarMouseEntered

    private void BConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BConsultarMouseExited
        BConsultar.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_BConsultarMouseExited

    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed

        int fila=TablaCitas.getSelectedRow(); //llamar tabla odontologo
        if (fila>-1) {
            String IDCita= TablaCitas.getValueAt(fila, 5).toString().trim();

            ConsultarCita destino = new ConsultarCita( nombre, CeduCar, Doc_Selec, IDCita);
            control.ConectarPanel(jPanel2, destino,  960, 639, 0, 0);

        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un odontólogo antes de consultar");
        }
       
    }//GEN-LAST:event_BConsultarActionPerformed

    private void BuscarTodoPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BuscarTodoPFocusGained
        if(BuscarTodoP.getText().equals("Ingrese datos de la cita...")){
            BuscarTodoP.setText("");

        }

        BuscarTodoP.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_BuscarTodoPFocusGained

    private void BuscarTodoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTodoPActionPerformed

    }//GEN-LAST:event_BuscarTodoPActionPerformed

    private void BuscarTodoPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarTodoPKeyPressed

        String[] columna = {"Nombre", "Cedula","Telefono", "Fecha", "Servicio","ID"}; 
        String[] registros = new String[7];
        TablaCitas.getTableHeader().setReorderingAllowed(false);
        DefaultTableModel dtm = new DefaultTableModel(null, columna) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String ssql = "SELECT * FROM citas WHERE Nombre LIKE '%" + BuscarTodoP.getText() + "%' "
        + "OR Cedula LIKE '%" + BuscarTodoP.getText() + "%'"
        + "OR Fecha LIKE '%" + BuscarTodoP.getText() + "%'"
        + "OR Telefono LIKE '%" + BuscarTodoP.getText() + "%'"
        + "OR ID LIKE '%" + BuscarTodoP.getText() + "%'"
        + "OR Servicio LIKE '%" + BuscarTodoP.getText() + "%'";
        try {
            Connection cn = Conexion.conectarBD();
            Statement stm = (Statement) cn.createStatement();
            ResultSet res = stm.executeQuery(ssql);

            while (res.next()) {

                registros[0] = res.getString(1); //nombre
                registros[1] = res.getString(2); //cedula
                registros[2] = res.getString(3); //Telefono
                registros[3] = res.getString(4); //Fecha
                registros[4] = res.getString(5); //Servicio
                registros[5] = res.getString(9); //Id
                registros[6]= res.getString(8); //Id
                if ("Secretaria".equals(Car) && Doc_Selec.equals(registros[6]) ) {
                    dtm.addRow(registros);
                } 
                if ("Odontologo".equals(Car) && Cedula_Usuario.equals(registros[6])) {
                    dtm.addRow(registros);
                }
            }
            TablaCitas.setModel(dtm);
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al filtrar desde la BD " + e);
            JOptionPane.showMessageDialog(null, "¡Contacte al administrador!");
        }
    }//GEN-LAST:event_BuscarTodoPKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro Agregar;
    private javax.swing.JButton BConsultar;
    private javax.swing.JTextField BuscarTodoP;
    private javax.swing.JLabel NombreOdo;
    private rsbuttom.RSButtonMetro Regresar;
    private javax.swing.JTable TablaCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneO;
    private Modelo.PanelRound panelRound1;
    private Modelo.PanelRound panelRound3;
    private Modelo.PanelRound panelRound4;
    // End of variables declaration//GEN-END:variables
}
